<?php

// $Id$

/**
 * @file
 * Module for displaying library hours for all libraries
 *
 * This is a heavily modified version of the libraryhours module written by John Fereira and
 * further developed by Jim Reidy.
 *
 */

/**
 * Implements hook_init()
 */
function cul_hours_init() {

  // Load the module's CSS and JS files.
  // TODO: set these to only load on the library hours page
  $module_path = drupal_get_path('module', 'cul_hours');

  if (request_path() == 'libraries') {
    drupal_add_css($module_path . '/cul_hours.css');
    drupal_add_js($module_path . '/cul_hours.js');
  }
  $base_url = $GLOBALS['base_url'];
  drupal_add_js(array('cul_hours' => array('module_path' => $base_url . '/' . drupal_get_path('module', 'cul_hours'))), array('type' => 'setting', 'scope' => JS_DEFAULT));
}

/**
 * Implements hook_exit().
 */
function cul_hours_exit() {
  // We've been having trouble with the hours display not updating properly because (I think)
  // the display is being cached. This should force the cached page to clear at the end of
  // every request.
  global $base_url;
  $url_pos = strpos($_GET['q'], 'hours');
  if ($url_pos !== FALSE) { // TODO: can we get rid of the hardcoded 'libraryhours'?
    cache_clear_all($base_url . '/' . $_GET['q'], 'cache_page');
  }
}

/**
 * Callback function for information about this module
 */
function cul_hours_about() {
  return theme('cul_hours_about');
}

/**
 * Implements hook_theme().
 */
function cul_hours_theme() {
  return array(
    'cul_hours_formatter_cul_hours_field_hours_id' => array(
      'variables' => array(
        'element' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_help().
 */
function cul_hours_help($path, $arg) {
  if ($path == 'admin/help#libraryhours') {
    $txt = 'The Library Hours module displays information about Library Hours';
    return '<p>' . t($txt) . '</p>';
  }
}

/* END HOOKS */


/**
 * Implements hook_field_formatter_info().
 */
function cul_hours_field_formatter_info() {
  return array(
    // the key must be unique, so it's best to prefix with your module's name.
    'cul_hours_field_hours_id' => array(
      // the label is is what is displayed in the select box in the UI.
      'label' => t('Library Hours listing with Open if appropriate'),
      // field types is the important bit!! List the field types your formatter is for.
      'field types' => array('text'),
      // You can usually leave 'multiple values' as follows:
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
    ),
  );
}

/**
 * Implements hook_field_formatter_view(). This code just passes straight
 * through to a theme function, cul_hours_formatter_FORMATTER
 * (e.g. cul_hours_formatter_cul_hours_absolute_url).
 */
function cul_hours_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $elements = array();
  foreach ($items as $delta => $item) {
    $elements[$delta] = array(
      '#markup' => theme('cul_hours_formatter_'. $display['type'], array('element' => $item, 'field' => $instance)),
    );
  }
  return $elements;
}

/**
 * Theme function for 'cul_hours_field_hours_id'  field formatter.
 */
function theme_cul_hours_formatter_cul_hours_field_hours_id($element) {
  if (isset($element['element']['safe_value'])) {
    $id = $element['element']['safe_value'];
    return cul_hours_dailyHoursFromId($id);
  }
}

function cul_hours_dailyHoursFromId($id) {

  $libcal_data = &drupal_static(__FUNCTION__);
  $output = 'unknown result';

  # Hacks for 'static' library hours
  if ($id == 'Engineering') {
    $output = "24/7 study space and computing only";
  }
  elseif ($id == 'PhysSci') {
   $output = "24/7 quiet study space only";
  }
  elseif ($id == 'weill' || $id == 'weill-archives') {
    $output = '';
  }
  else {
    // Translate the library name into the ID used by LibCal
    $libcal_codes = array(
      'Africana' => 3319,
      'Fine Arts' => 3321,
      'Hotel' => 3322,
      'ILR' => 3323,
      'Kroch' => 3324,
      'Rare' => 3325,
      'Law' => 3477,    // This is the ID for PUBLIC ACCESS to law
      'GENEVA' => 3437,
      'ANNEX' => 3326,
      'JGSM' => 3362,   // PUBLIC ACCESS ID
      'MANNLIB' => 1707,
      'MATH' => 3327,
      'Music' => 3328,
      'OLIN' => 2818,
      'Ornithology' => 3329,
      'Uris' => 2830,
      'Vet' => 3331
    );
    $library_id = $libcal_codes[$id];

    // The LibCal API provides a parameter (lid) that can be used to query just the hours for
    // a single library/location. However, there's a weird snag: for a library that has subordinate
    // locations (e.g., reference desk) and its own lid, the lid returned in the JSON *result* is
    // a zero (0). That makes it impossible to compare the results against the query, which one
    // might want to do when, say, only displaying the hours for the main library building. So
    // instead, we can just do one query to fetch today's hours for all the libraries, and then
    // cache that result.
    if (!isset($libcal_data)) {
      $url = "https://api3.libcal.com/api_hours_today.php?iid=973&lid=&format=json&nocache=1";
      $libcal_data = json_decode(file_get_contents($url));
    }

    foreach ($libcal_data->locations as $loc) {
      // Only do this for the main library building. Libraries may have additonal locations within
      // the main buildings, but we only want to return daily hours for the main location right now.
      if ($loc->lid == $library_id) {

        if ($loc->times->status == 'not-set') {
          $output = "Today's hours unavailable";
        }
        else {
          $open_now = ($loc->times->currently_open == 'true');

          $output = $loc->rendered;
          if ($output == '24 Hours') {
            $output = 'Open 24 hours';
          }
          if ($open_now === TRUE) {
            $output .= '   <span class="label label-success library-open">Open</span>';
          }
          else {
            $output .= '   <span class="label label-danger library-closed">Closed</span>';
          }
        }

        break;
      }
    }
  }
  #echo "output: $output";

  return $output;
}
